spring:
  application:
    name: estate-agent-gw
  cloud:
    gateway:
      routes:
        - id: estate-agent-user-service
          uri: lb://ESTATE-AGENT-USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
        - id: estate-agent-announcement-service
          uri: lb://ESTATE-AGENT-ANNOUNCEMENT-SERVICE
          predicates:
            - Path=/api/v1/announcements/**
        - id: estate-agent-package-service
          uri: lb://ESTATE-AGENT-PACKAGE-SERVICE
          predicates:
            - Path=/api/v1/packages/**
        - id: estate-agent-payment-service
          uri: lb://ESTATE-AGENT-PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payments/**

server:
  port: 8080
